# Generated by Django 3.2.9 on 2022-01-10 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('context', models.CharField(max_length=200)),
                ('cycle', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('version', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_by', models.CharField(max_length=200)),
                ('error_details', models.CharField(max_length=200)),
                ('output', models.TextField(blank=True)),
                ('severity', models.CharField(max_length=200)),
                ('fix', models.CharField(blank=True, max_length=200)),
                ('open_datetime', models.DateTimeField()),
                ('close_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
    ]
